const CUSTOMER_FETCH_STARTING= 'CUSTOMER_FETCH_STARTING'
const CUSTOMER_FETCH_SUCCESS= 'CUSTOMER_FETCH_SUCCESS'
const CUSTOMER_FETCH_FAILED= 'CUSTOMER_FETCH_FAILED'
const USER_TYPING_CUSTOMER_NAME= 'USER_TYPING_CUSTOMER_NAME'
const USER_TYPING_COMPLETED_CUSTOMER_NAME= 'USER_TYPING_COMPLETED_CUSTOMER_NAME'
const USER_TYPING_FAILED_CUSTOMER_NAME= 'USER_TYPING_FAILED_CUSTOMER_NAME'
export  {
    CUSTOMER_FETCH_STARTING,
    CUSTOMER_FETCH_SUCCESS,
    CUSTOMER_FETCH_FAILED,
    USER_TYPING_CUSTOMER_NAME,
    USER_TYPING_COMPLETED_CUSTOMER_NAME,
    USER_TYPING_FAILED_CUSTOMER_NAME
}